### ISSUE TITLE
zlib static binaries need to be recompiled with -fPIC to be compatible with PIE builds

### ISSUE THREAD

**Issue by genotrance** [JuliaBinaryWrappers/Zlib_jll.jl#1]

**Comment by giordano** [comment]
Why do you need the static binary at all?  We might even remove it in the future

**Comment by genotrance** [comment]
No static builds will be a big loss - creating standalone binaries makes distribution super easy.

This may or may not apply to Julia but I'm using these builds in Nim. I'm sure anyone working with C/C++ or other languages that leverage a C/C++ compiler behind the scenes will really appreciate the work being done here.

**Comment by StefanKarpinski** [comment]
Love that you’re using this for nim, very exciting!
